spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurants_owners_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
#  sql:
#    init:
#      schema-locations: schema.sql
#  liquibase:
#    enabled: true
#    change-log: db/changelog/changelog.yaml