spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurants_owners_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  liquibase:
    enabled: true
    change-log: db/changelog/changelog.yaml